version: "3.9"

services:
  backend:
    build: ./backend
    container_name: django_backend
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend:/app
    expose:
      - "8000"

  frontend:
    build: ./frontend
    container_name: nextjs_frontend
    restart: always
    env_file:
      - .env
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend